#!/bin/bash
# (C) 2022 - Onno VK6FLAB <cq@vk6flab.com>

# This script will repeatedly play an audio file with a 4 second pause between
# each time

if [ $# -ne 1 ]
then
	echo "Usage: $0 audioFile"
	exit 1
fi

if [ ! -f "$1" ]
then
	echo "Error: '$1' file not found, aborting."
	exit 1
fi

trap "exit" INT

while true
do
	echo -n "Playing: $1 ."
	play -q "$1" -t alsa
	echo ". done"
	echo -n "Sleeping ."
	sleep 4
	echo ". done"
done
