#!/bin/bash
# (C) 2022 - Onno VK6FLAB <cq@vk6flab.com>

# Output a spectrogram for each supplied filename

for this_file in "$@"
do
	output_dir=$(dirname "${this_file}")
	output_file=$(basename "${this_file}" .wav)

	if [ ! -s "${output_dir}/${output_file}.wav" ]
	then
		continue
	fi

	if [ ! -f "${output_dir}/${output_file}.png" ]
	then
		title=$(date -r "${this_file}" "+Spectrogram of transmission ending on %Y-%m-%d at %H:%M:%S")
		credit="Credits: SoX, VK6FLAB"
		sox "${this_file}" -n spectrogram -t "${title}" -c "${credit}" -o "${output_dir}/${output_file}.png"
	fi
done
